### ISSUE TITLE
AUfruf funktioniert nicht: Wird umgeleutet auf Default

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-multilang#10]
ich hab eine englische Seite angelegt , bearbeitet und gespeichert:
![grafik](https://user-images.githubusercontent.com/1070669/109151986-cb862a80-7762-11eb-9c1d-ce5176b6f3e9.png)

Beim Klick auf den Link, der in der URI mit /en/ beginnt, werde ich dennoch auf die deutsche Seite zurückgeleitet.

**Comment by xwolfde** [comment]
Permalinks update half auch nicht

**Comment by rvdforst** [comment]
bug fixed! -> v. 1.0.9
