### ISSUE TITLE
Erwähnung nicht existierender Sprachversion im Sprachschalter

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-multilang#11]
IMHO macht es keinen Sinn, eine Sprache, die zwar festgelegt ist, aber zu der es noch keine Übersetzung gibt, anzuzeigen:

![grafik](https://user-images.githubusercontent.com/1070669/109152483-7860a780-7763-11eb-931f-6211107bf6fa.png)

Wenn es die Übersetzung noch nicht gibt, sollte es auch keine Anzeige dazu geben. Außer in dem Fall, dass eine Fallback-Seite pro Sprache angegeben wurde, wo im Falle von nicht existierender Übersetzung hingelinkt wird.

**Comment by xwolfde** [comment]
ggf. zur dynamischen Entscheidung folgende CSS-Klasse ergänzen, wenn kein Link da ist:

`<li class="eo nonexisting" lang="eo">Esperanto</li>`

**Comment by rvdforst** [comment]
Jetzt sieht es so aus (V. 1.0.2):
- Ohne Standardseite:
```
<nav aria-label="Sprachwechsler">
    <li class="en-GB en notranslation">English</li>
    <li class="es-ES es notranslation">Español</li>
</nav>
```
- Mit Standardseite:
```
<nav aria-label="Sprachwechsler">
    <li class="en-GB en"><a rel="alternate" hreflang="en"
            href="https://www.site.de.localhost/404-fehler/">English</a></li>
    <li class="es-ES es"><a rel="alternate" hreflang="es"
            href="https://www.site.de.localhost/404-fehler/">Español</a></li>
</nav>
```

Standardseite: Die Seite, auf die umgeleitet werden soll, wenn die Übersetzung nicht vorhanden ist.
