### ISSUE TITLE
CMS Workflow und Multilang: Widgets verwechslungsfähig

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-multilang#12]
Wenn beide Plugins an sind,  werden beide WIdgets mit selben Titel unter WIdgets angezeigt:
![grafik](https://user-images.githubusercontent.com/1070669/109152922-0d63a080-7764-11eb-8cab-27ea270c9062.png)

**Comment by rvdforst** [comment]
Jetzt wird der mehrsprachige Modus des Multilang-Plugins automatisch deaktiviert, wenn das Netzwerk- oder das Übersetzungsmodul des Workflow-Plugins aktiviert ist. D. h., nur eines der Widgets kann verfügbar sein.
