### ISSUE TITLE
Strings in Single-Ansichten von Custom Post Types werden nicht übersetzt 

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-multilang#28]
Konkret: Plugin rrze-expo
Nicht hierarchische Custom Post Types, wie z.B. Messestand (booth)
Multilang-Option: Single Site

Problem: Bei der Anzeige der englischen Version werden die Inhalte des Posts übersetzt, aber nicht die im Template (single-booth.php) integrierten Strings (Zwischenüberschriften "Kontakt", "Info-Material" etc.). Die Strings sind im Template als übersetzbar angelegt, und im Plugin übersetzt.
![Bildschirmfoto 2021-07-27 um 14 55 38](https://user-images.githubusercontent.com/4435815/136920382-eda10a7e-e627-4936-8381-8378e4bba64b.png)

**Comment by rvdforst** [comment]
Ich denke, das Problem wurde behoben.
