### ISSUE TITLE
Hinzufügen von Übersetzungen benötigt Administrator-Rechte

### ISSUE THREAD

**Issue by MichaelEischer** [RRZE-Webteam/rrze-multilang#30]
## Verwendetes Setup
Wordpress 5.8.2
Aktuellste Sourcecode-Version von rrze-multilang
Aktivierter Modus: "Einzelne Webseite", Sprachen: Deutsch und Englisch.

## Reproduktion
Neue Seite erstellen und speichern. Anschließend sollte die Möglichkeit bestehen eine Übersetzung hinzuzufügen.

## Erwartetes Verhalten
- Ein Nutzer kann eigenen Seiten eine übersetzte Version hinzufügen.
- Ein Nutzer mit "Redakteur"-Rechten kann zu beliebigen Seiten Übersetzungen erstellen

## Tatsächliches Verhalten
Nur Nutzer mit Administratorrechten können Übersetzungen für eine Seite anlegen.

## Vermutete Ursache
Nur Nutzer mit der "manage_options"-Berechtigung können Übersetzungen für alle Sprachen erstellen:
https://github.com/RRZE-Webteam/rrze-multilang/blob/9b56bc2bf0c5a32c138b3e56deec037ea2acdf04/includes/Single/Capabilities.php#L18

Es scheint ein Mechanismus vorgesehen zu sein, einzelnen Nutzern Zugriff auf mehr als nur die Standardsprache zu geben, allerdings sehe ich keine einfache Möglichkeit diesen zu nutzen.
https://github.com/RRZE-Webteam/rrze-multilang/blob/9b56bc2bf0c5a32c138b3e56deec037ea2acdf04/includes/Single/Users.php#L210

**Comment by rvdforst** [comment]
Die Capabilities wurden wie folgt angepasst:
```
$metaCaps = [
    'rrze_multilang_edit_terms_translations' => 'manage_categories',
    'rrze_multilang_access_all_locales' => 'edit_published_posts',
    'rrze_multilang_access_locale' => 'read'
];
```
D.h., die Redakteure können auch Übersetzungen von Beiträgen und Seiten hinzufügen, die von anderen Nutzern veröffentlicht wurden. Die Autoren dürfen nur Übersetzungen der Beiträge hinzufügen, die sie selbst veröffentlicht haben.
