### ISSUE TITLE
Template Startseite Fakultät

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-multilang#36]
Beiträge erscheinen im Slider (Template Startseite Fakultät) sowohl auf Deutsch + Fremdsprache (Spanisch)
<img width="1739" alt="Bildschirmfoto 2022-06-27 um 15 30 46" src="https://user-images.githubusercontent.com/58593037/175953675-ea90ff13-4154-44f0-abe8-f4e1a387f368.png">
<img width="1739" alt="Bildschirmfoto 2022-06-27 um 15 31 16" src="https://user-images.githubusercontent.com/58593037/175953774-ce6d4739-c444-43e1-9474-1232d8ed374e.png">

**Comment by rvdforst** [comment]
Der Ursprung des Problems liegt nicht im Plugin, sondern im Theme. Das Theme nutzt Beiträge auf unkonventionelle Weise, um den Inhalt des Sliders anzuzeigen, ohne zu berücksichtigen, dass möglicherweise ein aktives Sprach-Plugin vorhanden ist. Die Lösung für diese Inkompatibilität befindet sich derzeit im Dev-Branch des betreffenden Theme-Repositorys.
