### ISSUE TITLE
Translated page not found

### ISSUE THREAD

**Issue by AndyFau** [RRZE-Webteam/rrze-multilang#49]
Ich habe für die Seite https://www.eei.tf.fau.de/studium/praktikumsamt/ eine englische Seite angelegt:
https://www.eei.tf.fau.de/en/studium/internship-office/

Beim Aufruf kommt "Error: Page not found". Auch das Umschalten auf Deutsch funktioniert dann nicht, die Seite wird nicht gewechselt. 

Als Hinweis, ich hab den Permalink der Englischen Seite von praktikumsamt auf internship-office geändert.

**Comment by rvdforst** [comment]
Wenn eine Unterseite übersetzt wird, muss auch die Hauptseite übersetzt werden, damit das Plugin funktioniert. In diesem Fall muss auch die Seite https://www.eei.tf.fau.de/studium/ ins Englische übersetzt werden. Vgl. https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/rrze-multilang/mehrsprachigen-webauftritt-mit-einer-einzelnen-instanz-bereitstellen/
