### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-multilang#8]
Wenn ich bei der Startseite einer Website (URI ist dann "/") eine anderssprache Version ergänze, wird die nicht unter einer neuen SLug gespeichert, sondern überschreibt die vorherige Defaultversion.

**Comment by xwolfde** [comment]
(Modus mit einer einzigen Website)

**Comment by rvdforst** [comment]
Ich denke, das wurde in V. 1.0.9 behoben (muss überprüft werden)
