### ISSUE TITLE
Target="_blank" im Editor bei Sprache wechseln

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-multilang#9]
Wenn ich von einer Editorseite zur anderen wechsle, geht das immer in einem neuen Fenster. Ein Fenster ok, aber jedesmal ein neuen ist doch doof?
Sehr häufig springe ich doch von einer Sprache zurück zur anderen. Wenn ich dann von deutsch auf englisch und dann zurück auf englisch springe, hab ich 3 Fenster. Davon 2, die in Konflikt stehen werden.

![grafik](https://user-images.githubusercontent.com/1070669/109151178-bfe63400-7761-11eb-8125-36a472f3af16.png)

**Comment by rvdforst** [comment]
Dev-Branch:
Der target-Attribut wurde auf default (_self) geändert (einschließlich Gutenberg).
